functionality:
  name: plot_map
  namespace: civ6_save_renderer
  description: "Use the settings yaml and the map tsv to generate a plot (as PDF)."
  version: "1.0"
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [maintainer, author]
      props: {github: rcannood, orcid: 0000-0003-3641-729X}
  arguments:
    - name: "--yaml"
      alternatives: [-y]
      type: file
      required: true
      default: "header.yaml"
      must_exist: true
      description: "A YAML file containing civ6 game settings information."
    - name: "--tsv"
      alternatives: [-t]
      type: file
      required: true
      default: "map.tsv"
      must_exist: true
      description: "A TSV file containing civ6 map information."
    - name: "--output"
      alternatives: [-o]
      type: file
      required: true
      default: "output.pdf"
      direction: output
      description: "Path to store the output PDF file at."
  resources:
    - type: r_script
      path: script.R
    - path: helper.R
platforms:
  - type: docker
    image: rocker/tidyverse
    r:
      cran:
        - ggforce
        - yaml
        - bit64
        - ggnewscale
        - cowplot
      github:
        - rcannood/civ6saves
  - type: nextflow
  - type: native
