functionality:
  name: parse_map
  namespace: civ6_save_renderer
  description: "Extract map information from a Civ6 save file as a tsv."
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      required: true
      default: "save.Civ6Save"
      must_exist: true
      description: "A Civ6 save file."
    - name: "--output"
      alternatives: [-o]
      type: file
      required: true
      default: "output.tsv"
      direction: output
      description: "Path to store the output TSV file at."
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: node
    docker:
      run: 
        - cd /home/node && git clone https://github.com/rcannood/civ6save-editing.git
  - type: nextflow
  - type: native
