functionality:
  name: parse_map
  namespace: civ6_save_renderer
  description: "Extract map information from a Civ6 save file as a tsv."
  version: "1.0"
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [maintainer, author]
      props: {github: rcannood, orcid: 0000-0003-3641-729X}
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      required: true
      default: "save.Civ6Save"
      must_exist: true
      description: "A Civ6 save file."
    - name: "--output"
      alternatives: [-o]
      type: file
      required: true
      default: "output.tsv"
      direction: output
      description: "Path to store the output TSV file at."
  resources:
    - type: javascript_script
      path: script.js
    - path: helper.js
platforms:
  - type: docker
    image: node
  - type: nextflow
  - type: native
