functionality:
  name: "build_rmd"
  version: 0.0.1
  description: |
    Build the viash docs Rmds to mds
  arguments:
    - name: "viash_docs"
      type: file
      description: The root of the viash_docs folder.
      default: "."
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: docker:dind
    privileged: true
    setup:
      # viash dependencies
      - type: apk
        packages: [ openjdk8-jre ]
      # viash
      - type: docker
        run:
          - wget https://github.com/data-intuitive/viash/releases/download/0.4.0/viash && chmod +x viash && mv viash /usr/local/bin
      # r dependencies
      - type: docker
        run:
          - "apk add --update-cache --repository http://nl.alpinelinux.org/alpine/v3.11/main autoconf=2.69-r2 automake=1.16.1-r0"
          - echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
          - apk add --no-cache cmark@testing pandoc@testing
      - type: apk
        packages: [ bash, R, R-dev, libcurl, g++, gcc, linux-headers, gfortran, automake, libtool, m4, autoconf, linux-headers, openssl, R, R-dev, wget, R-doc libxml2 libxml2-dev libc-dev ]
      # r setup
      - type: docker
        env:
          - CRAN="https://cran.rstudio.com"
          - R_HOME="/usr/lib/R"
        run:
          - echo "options(repos = c(CRAN = '${CRAN}'))" >> ${R_HOME}/etc/Rprofile.site
      # R packages
      - type: r
        cran: [ blogdown, rmarkdown, tidyverse ]
        github: [ tidyverse/readxl ] # cran version of readxl doesn't work with alpine yet
      - type: r
        cran: [ tidyverse ]
      # python
      - type: apk
        packages: [ python3 ]
      - type: docker
        run: [ ln -sf python3 /usr/bin/python ]
      # documentation example dependancies
      - type: apk
        packages: [ curl ]