functionality:
  name: "run_server"
  version: 0.0.1
  description: |
    Run the viash docs server locally.
  arguments:
    - name: "viash_docs"
      type: file
      description: The root of the viash_docs folder.
      default: "."
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: jekyll/jekyll
    port: [ 4000:4000 ]
    setup:
      - type: apk
        packages: [ ruby ]
