functionality:
  name: plot_map
  namespace: civ6_save_renderer
  arguments:
    - name: "--yaml"
      alternatives: [-y]
      type: file
      required: true
      default: "header.yaml"
      must_exist: true
    - name: "--tsv"
      alternatives: [-t]
      type: file
      required: true
      default: "map.tsv"
      must_exist: true
    - name: "--output"
      alternatives: [-o]
      type: file
      required: true
      default: "output.pdf"
      direction: output
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: rocker/tidyverse
    r:
      cran:
        - ggforce
        - yaml
        - bit64
        - ggnewscale
      github:
        - rcannood/civ6saves
