functionality:
  name: hello_world_r
  description: A very simple 'Hello world' component.
  arguments:
  - type: string
    name: input
    multiple: true
    multiple_sep: " "
  - type: string
    name: --greeter
    default: "Hello world!"
  resources:
  - type: r_script
    path: script.R
  tests:
  - type: r_script
    path: test.R
platforms:
  - type: native
  - type: docker
    image: "rocker/tidyverse:4.0.4"
