functionality:
  name: md_url_checker_r
  description: Check if URLs in a markdown are reachable and create a text report with the results.
  arguments:                     
  - type: file
    name: --inputfile
    description: The input markdown file.
    required: true
    must_exist: true
  - type: string                           
    name: --domain
    description: The domain URL that gets inserted before any relative URLs. For example, "/documentation/intro" could be replaced with "https://my-website/documentation/intro" to create a valid URL.
  - type: file                           
    name: --output
    description: The path of the output text file that will contain the report.
    default: "output.txt"
    direction: output
  - type: file                           
    name: --temp_html
    description: The path of the temporary html file.
    default: "temp.html"
    direction: output
  resources:
  - type: r_script
    path: script.R
platforms:
  - type: native
  - type: docker
    image: "rocker/tidyverse:latest"
    setup:
    - type: apt
      packages:
        - pandoc