functionality:
  name: hello_world_py
  description: A very simple 'Hello world' component.
  arguments:
  - type: string
    name: input
    multiple: true
    multiple_sep: " "
  - type: string
    name: --greeter
    default: "Hello world!"
  resources:
  - type: python_script
    path: script.py
  tests:
  - type: python_script
    path: test.py
platforms:
  - type: native
  - type: docker
    image: "python:3.8"
